version: "3"

services:
  excloud1_mysql:
    container_name: excloud1_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - excloud1_mysql:/var/lib/mysql
      - ./create_empty_arrowhead_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  excloud1_serviceregistry:
    container_name: excloud1_serviceregistry
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/serviceregistry:latest
    depends_on:
      - excloud1_mysql
    volumes:
      - ./excloud1/certificates/keystore.sreg.excloud1.p12:/serviceregistry/certificates/keystore.sreg.excloud1.p12
      - ./excloud1/certificates/truststore.excloud1.p12:/serviceregistry/certificates/truststore.excloud1.p12
      - ./excloud1/configs/serviceregistry.properties:/serviceregistry/application.properties
    ports:
      - 8443:8443

  excloud1_authorization:
    container_name: excloud1_authorization
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/authorization:latest
    depends_on:
      - excloud1_mysql
      - excloud1_serviceregistry
    volumes:
      - ./excloud1/certificates/keystore.auth.excloud1.p12:/serviceregistry/certificates/keystore.auth.excloud1.p12
      - ./excloud1/certificates/truststore.excloud1.p12:/serviceregistry/certificates/truststore.excloud1.p12
      - ./excloud1/configs/authorization.properties:/authorization/application.properties
    ports:
      - 8445:8445

  excloud1_orchestrator:
    container_name: excloud1_orchestrator
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/orchestrator:latest
    depends_on:
      - excloud1_mysql
      - excloud1_serviceregistry
      - excloud1_gatekeeper
    volumes:
      - ./excloud1/certificates/keystore.orch.excloud1.p12:/serviceregistry/certificates/keystore.orch.excloud1.p12
      - ./excloud1/certificates/truststore.excloud1.p12:/serviceregistry/certificates/truststore.excloud1.p12
      - ./excloud1/configs/orchestrator.properties:/orchestrator/application.properties
    ports:
      - 8441:8441

  excloud1_eventhandler:
    container_name: excloud1_eventhandler
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/eventhandler:latest
    depends_on:
      - excloud1_mysql
      - excloud1_serviceregistry
    volumes:
      - ./excloud1/certificates/keystore.evth.excloud1.p12:/serviceregistry/certificates/keystore.evth.excloud1.p12
      - ./excloud1/certificates/truststore.excloud1.p12:/serviceregistry/certificates/truststore.excloud1.p12
      - ./excloud1/configs/eventhandler.properties:/eventhandler/application.properties
    ports:
      - 8455:8455
  
  excloud1_gatekeeper:
    container_name: excloud1_gatekeeper
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/gatekeeper:latest
    depends_on:
      - excloud1_mysql
      - excloud1_serviceregistry
    volumes:
      - ./excloud1/certificates/keystore.gkep.excloud1.p12:/serviceregistry/certificates/keystore.gkep.excloud1.p12
      - ./excloud1/certificates/truststore.excloud1.p12:/serviceregistry/certificates/truststore.excloud1.p12
      - ./excloud1/configs/gatekeeper.properties:/gatekeeper/application.properties
    ports:
      - 8449:8449

  excloud1_gateway:
    container_name: excloud1_gateway
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/gateway:latest
    depends_on:
      - excloud1_mysql
      - excloud1_serviceregistry
    volumes:
      - ./excloud1/certificates/keystore.gway.excloud1.p12:/serviceregistry/certificates/keystore.gway.excloud1.p12
      - ./excloud1/certificates/truststore.excloud1.p12:/serviceregistry/certificates/truststore.excloud1.p12
      - ./excloud1/configs/gateway.properties:/gateway/application.properties
    ports:
      - 8453:8453 

volumes:
  excloud1_mysql:
    external: true
