version: "3"

services:
  activemq:
     container_name: activemq
     image: rmohr/activemq:latest
     volumes:
        - ./conf/activemq.xml:/conf/activemq.xml
     ports:
        - 61616:61616
        - 8161:8161

