version: "3"

services:

  ############################################
  ###         DATA CONSUMER CLOUD          ###
  ############################################

  consumer_mysql:
    container_name: consumer_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - consumer_mysql_vol:/var/lib/mysql
      - ./create_empty_arrowhead_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  consumer_authorization:
    container_name: consumer_authorization
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/authorization:latest
    depends_on:
      - consumer_mysql
      - consumer_serviceregistry
    volumes:
      - ./cloud-data-consumer/authorization.properties:/authorization/application.properties
    ports:
      - 8441:8441

#  consumer_contract_system:
#    container_name: consumer_contract_system
#    image: TODO
#    depends_on:
#      - consumer_mysql
#      - consumer_orchestrator
#      - consumer_serviceregistry
#    volumes:
#      - ./cloud-data-consumer/contractsystem.properties:/contractsystem/application.properties
#    ports:
#      - 8442:8442

  #  consumer_data_producer:
  #    container_name: consumer_data_producer
  #    image: TODO
  #    depends_on:
  #      - consumer_mysql
  #      - consumer_orchestrator
  #      - consumer_serviceregistry
  #      - consumer_contract_system
  #    volumes:
  #      - ./cloud-data-consumer/dataproducer.properties:/dataproducer/application.properties
  #    ports:
  #      - 8443:8443

  consumer_eventhandler:
    container_name: consumer_eventhandler
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/eventhandler:latest
    depends_on:
      - consumer_mysql
      - consumer_serviceregistry
    volumes:
      - ./cloud-data-consumer/eventhandler.properties:/eventhandler/application.properties
    ports:
      - 8444:8444

  consumer_gatekeeper:
    container_name: consumer_gatekeeper
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/gatekeeper:latest
    depends_on:
      - consumer_mysql
      - consumer_serviceregistry
    volumes:
      - ./cloud-data-consumer/gatekeeper.properties:/gatekeeper/application.properties
    ports:
      - 8445:8445

  consumer_gateway:
    container_name: consumer_gateway
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/gateway:latest
    depends_on:
      - consumer_mysql
      - consumer_serviceregistry
    volumes:
      - ./cloud-data-consumer/gateway.properties:/gateway/application.properties
    ports:
      - 8446:8446

  consumer_orchestrator:
    container_name: consumer_orchestrator
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/orchestrator:latest
    depends_on:
      - consumer_mysql
      - consumer_serviceregistry
      - consumer_gatekeeper
    volumes:
      - ./cloud-data-consumer/orchestrator.properties:/orchestrator/application.properties
    ports:
      - 8447:8447

  consumer_serviceregistry:
    container_name: consumer_serviceregistry
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/serviceregistry:latest
    depends_on:
      - consumer_mysql
    volumes:
      - ./cloud-data-consumer/serviceregistry.properties:/serviceregistry/application.properties
    ports:
      - 8448:8448

  ############################################
  ###         DATA PRODUCER CLOUD          ###
  ############################################

  producer_mysql:
    container_name: producer_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - producer_mysql_vol:/var/lib/mysql
      - ./create_empty_arrowhead_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3307

  producer_authorization:
    container_name: producer_authorization
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/authorization:latest
    depends_on:
      - producer_mysql
      - producer_serviceregistry
    volumes:
      - ./cloud-data-producer/authorization.properties:/authorization/application.properties
    ports:
      - 8541:8541

  #  producer_contract_system:
  #    container_name: producer_contract_system
  #    image: TODO
  #    depends_on:
  #      - producer_mysql
  #      - producer_orchestrator
  #      - producer_serviceregistry
  #    volumes:
  #      - ./cloud-data-producer/contractsystem.properties:/contractsystem/application.properties
  #    ports:
  #      - 8542:8542

  #  producer_data_producer:
  #    container_name: producer_data_producer
  #    image: TODO
  #    depends_on:
  #      - producer_mysql
  #      - producer_orchestrator
  #      - producer_serviceregistry
  #      - producer_contract_system
  #    volumes:
  #      - ./cloud-data-producer/dataproducer.properties:/dataproducer/application.properties
  #    ports:
  #      - 8543:8543

  producer_eventhandler:
    container_name: producer_eventhandler
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/eventhandler:latest
    depends_on:
      - producer_mysql
      - producer_serviceregistry
    volumes:
      - ./cloud-data-producer/eventhandler.properties:/eventhandler/application.properties
    ports:
      - 8544:8544

  producer_gatekeeper:
    container_name: producer_gatekeeper
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/gatekeeper:latest
    depends_on:
      - producer_mysql
      - producer_serviceregistry
    volumes:
      - ./cloud-data-producer/gatekeeper.properties:/gatekeeper/application.properties
    ports:
      - 8545:8545

  producer_gateway:
    container_name: producer_gateway
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/gateway:latest
    depends_on:
      - producer_mysql
      - producer_serviceregistry
    volumes:
      - ./cloud-data-producer/gateway.properties:/gateway/application.properties
    ports:
      - 8546:8546

  producer_orchestrator:
    container_name: producer_orchestrator
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/orchestrator:latest
    depends_on:
      - producer_mysql
      - producer_serviceregistry
      - producer_gatekeeper
    volumes:
      - ./cloud-data-producer/orchestrator.properties:/orchestrator/application.properties
    ports:
      - 8547:8547

  producer_serviceregistry:
    container_name: producer_serviceregistry
    image: portus.arrowhead-ci.tmit.bme.hu/arrowhead/serviceregistry:latest
    depends_on:
      - producer_mysql
    volumes:
      - ./cloud-data-producer/serviceregistry.properties:/serviceregistry/application.properties
    ports:
      - 8548:8548

volumes:
  consumer_mysql_vol:
    external: true
  producer_mysql_vol:
    external: true
